# --------------------------------------------------------------------------- #
# Developer: Andrew Kirfman                                                   #
# Project: CSCE-313 Machine Problem #4                                                #
#                                                                             #
# File: ./Makefile                                                            #
# --------------------------------------------------------------------------- #


CC=g++
STD=-std=c++11
CFLAGS=-O3 -Wall -g


all: shell.cpp
	$(CC) $(CFLAGS) $(STD) shell.cpp -o shell

clean:
	rm -rf shell
